### ISSUE TITLE
SanitizersServiceProvider typo

### ISSUE THREAD

**Issue by erik-stephens** [lukzgois/sanitizer#1]
Ei, capitão!  Eu não conseguiria usar ate eu mudei o nome deste arquivo (SanitizerServiceProvider.php):

https://github.com/lukzgois/sanitizer/blob/master/src/Laravel/SanitizersServiceProvider.php

**Comment by lukzgois** [comment]
Putz, vdd,
ficou no plural, vou enviar um commit pra corrigir isso

**Comment by lukzgois** [comment]
Enviei uma correção @erik-stephens, verifica se irá resolver o problema.
att

**Comment by erik-stephens** [comment]
Tá certo.  Obrigrado!
